### ISSUE TITLE
Rokit token validation fails in GitHub Actions

### ISSUE THREAD

**Issue by CompeyDev** [rojo-rbx/rokit#53]
When providing a GitHub Action token (via `${{ secrets.GITHUB_TOKEN }}`), Rokit considers the provided token invalid, and errors.

![image](https://github.com/user-attachments/assets/0d58a5b9-014e-49d3-b3dc-5f4100fef776)

I've not investigated this much, so I'm not really sure whether action tokens are of a different pattern - if anyone else can repro this, lmk how.

**Comment by filiptibell** [comment]
Fixed in #60
