### ISSUE TITLE
Add support for shortcuts.

### ISSUE THREAD

**Issue by kineticwallet** [rojo-rbx/rokit#55]
For example: `i` for `install`, `a` for `add`, etc

**Comment by filiptibell** [comment]
Thinking about this some more, I don't think the usefulness weighs heavily enough for us to add shortcuts for Rokits subcommands. Here is my reasoning:

- `rokit` itself is a somewhat long name, so `rokit a tool-author/tool-name` versus `rokit add tool-author/tool-name` for example goes from 41 characters to 39
- Almost all shortcuts will be ambigous.
  - Is `rokit i` the same as `rokit init` or `rokit install`?
  - Is `rokit a` the same as `rokit add` or `rokit authenticate`?
  - Is `rokit si` the same as `rokit self-install` or `rokit system-info`?
  - ...
- Rokit commands are not meant to run very often. You might make commits every few minutes, so `git` having shortcuts is valuable, while Rokit usage may happen once a day, once a week, or once a month. Maybe even less.
- Preserving user-friendliness of the commands is important and I would not like for people to start recommending `rokit i` over `rokit install` in documentation for their tools. New users have no idea what "i" could mean.
