### ISSUE TITLE
Installer for Windows does not work properly

### ISSUE THREAD

**Issue by greatinternetmachine** [rojo-rbx/rokit#59]
Does not seem to be adding to PATH correctly, as it is not recognizing "rokit" as a valid command

**Comment by filiptibell** [comment]
Does this issue still persist after:
- Logging out + logging back in again?
- Restarting your computer?

Changing PATH on Windows sometimes does not apply immediately and it is a bit unclear what fixes it. Make sure to try both of the above. If neither of them work, could you try running `./rokit.exe system-info` in a terminal, inside the folder where you downloaded Rokit, and showing the output of that command?

**Comment by filiptibell** [comment]
Closing this issue since it was most likely because a restart was necessary. Feel free to open this back up if the issue persists
