### ISSUE TITLE
tools installed with rokit having issues with stdio

### ISSUE THREAD

**Issue by AshleyFlow** [rojo-rbx/rokit#61]
Ive been having troubles with using the stdio library and the repl command in lune recently, and Ive figured out that this only happens when I install lune using rokit, Ive tested this on other releases of lune aswell so Im sure this is related to rokit
### ✅ repl command with manual install:
![image](https://github.com/user-attachments/assets/42234f79-909e-433b-8ddb-7d31756d9b66)

### ❌ repl command with rokit install:
![image](https://github.com/user-attachments/assets/8c10600d-7e06-429e-a473-005af725e6ad)

**Comment by filiptibell** [comment]
Ugh. Looks like this is (once again) an issue with the `command-group` crate and how it wraps spawned programs. Will need some further investigation...
